version: 2
jobs:
  build:
    working_directory: ~/mazimkhan/mbedtls
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: armmbed/mbedtls-ubuntu-16.04:0.0.1
      command: /sbin/init
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run: ./tests/scripts/builder.py campaigns -r all-tests
    filters:
      branches:
        only: jenkinsfile
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-development-
        - v1-dep-
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
