# Mbed TLS CircleCI 2.0 configuration file
#

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: armmbed/mbedtls-ubuntu-16.04:0.0.1

version: 2
jobs:
  scm:
    working_directory: ~/repo
    docker:
      - image: armmbed/mbedtls-ubuntu-16.04:0.0.1

    steps:
      - checkout:
          path: src

      - persist_to_workspace:
          root: ~/repo
          paths:
            - src

      - run:
          name: echo
          command: echo "Hello World"

      - run:
          name: list files
          command: ls -ltr;echo "***************";ls -ltr /
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: list files
          command: ls -ltr

workflows:
  version: 2
  btd:
    jobs:
      - scm
      - release:
          requires:
            - scm
