# Mbed TLS CircleCI 2.0 configuration file
#

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: armmbed/mbedtls-ubuntu-16.04:0.0.1

version: 2
jobs:
  scm:
    working_directory: ~/
    docker:
      - image: armmbed/mbedtls-ubuntu-16.04:0.0.1

    steps:
      - checkout:
          path: mbedtls

      - persist_to_workspace:
          root: ~/
          paths:
            - mbedtls
  sample_job:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: list files
          command: ls -ltr mbedtls/

workflows:
  version: 2
  sample_workflow:
    jobs:
      - scm
      - sample_job:
          requires:
            - scm
