
node {
    deleteDir()
    checkout([$class: 'GitSCM', branches: [[name: BRANCH]],
        doGenerateSubmoduleConfigurations: false,
        extensions: [[$class: 'CloneOption', honorRefspec: true,
        noTags: true, reference: '', shallow: true]],
        submoduleCfg: [],
        userRemoteConfigs: [[credentialsId: "${env.GIT_CREDENTIALS_ID}",
        url: MBEDTLS_REPO]]])
    sh """
pwd
ls -ltr
cd jenkins/
python cibuilder.py ${env.JOB_NAME} > tests.txt
    """
    tests = readFile 'tests.txt'
    def test_list = tests.split( '\n' )
    for( test in test_list) {
        def test_details = test.split( '|' )
        def test_name = test_details[0]
        def test_script = test_details[1]
        def label = test_details[2]
        echo "${test_name} ${test_script} ${label}"
    }
}

